In [17]:
# env : local 
# 2020.09.12

# importing example
import numpy as np

In [18]:
# linear structure define
vec = np.array([1, 2])
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

In [19]:
# Summation, Subtract, Scalar multiplication of linear structure
a = np.array([1, 2])
b = np.array([3, 4])

print(a + b)
print(np.add(a, b))

print(a - b)
print(np.subtract(a, b))

print(3 * a)
print(np.multiply(3, a))

[4 6]
[4 6]
[-2 -2]
[-2 -2]
[3 6]
[3 6]


In [20]:
# Inner product and outer product of vector
print(np.inner(a, b))
print(np.outer(a, b))

11
[[3 4]
 [6 8]]


In [24]:
# Shape of matrix
print(np.shape(vec))
print(np.shape(mat))

(2,)
(2, 3)


In [28]:
# Reshaping the matrix
dim_mat = np.shape(mat)
mat_to_vec = np.reshape(mat, dim_mat[0] * dim_mat[1])
mat_to_mat1 = np.reshape(mat, [3, 2])
mat_transpose = mat.T

print(mat)
print(mat_to_vec)
print(mat_to_mat1)
print(mat_transpose)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [34]:
# 2-norm of vector
print(a)
print(np.linalg.norm(a))

# Frobenius norm of matrix
print(np.linalg.norm(mat))

[1 2]
2.23606797749979
9.539392014169456
