In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : Binarization
#

In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])
print(X)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [4]:
binarizer = preprocessing.Binarizer(threshold=0)
X_bin = binarizer.transform(X)
print(X_bin)

[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
