In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : One Hot Encoding
#

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer

In [5]:
color = ['red', 'green', 'blue']

In [11]:
color_num = LabelEncoder().fit_transform(color)
print(color_num)

color_onehot = OneHotEncoder().fit_transform(color_num.reshape(-1, 1))
print(color_onehot) # 희소 행렬 형태
lor_num = LabelEncoder().fit_transform(color)
print(color_num)

color_onehot = OneHotEncoder().fit_transform(color_num.reshape(-1, 1))
print(color_onehot) # 희소 행렬 형태
print(color_onehot.toarray()) # 일반 행렬 형태

[2 1 0]
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
[2 1 0]
  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [13]:
color_onehot2 = LabelBinarizer().fit_transform(color)
print(color_onehot2)

[[0 0 1]
 [0 1 0]
 [1 0 0]]
