In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : Standardization of data
#

In [2]:
from sklearn import preprocessing
import numpy as np

In [8]:
print("Data " + '=' * 20)
X_train = np.array([[1., -1., 2.],
                    [2., 0., 0.],
                    [0., 1., -1.]])
print("\nBefore Standardization " + '-' * 20)
print(X_train)

X_scaled = preprocessing.scale(X_train)
print("\nAfter Standardization " + '-' * 20)
print(X_scaled)

Data ====================

Before Standardization --------------------
[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]

After Standardization --------------------
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [12]:
print("Mean and standard-deviation " + '=' * 20)

print("\nBefore Standarization " + '-' * 20)
print("mean " + str(X_train.mean(axis=0)))
print("var  " + str(X_train.var(axis=0)))

print("\After Standarization " + '-' * 20)
print("mean " + str(X_scaled.mean(axis=0)))
print("var  " + str(X_scaled.var(axis=0)))

Mean and standard-deviation ====================

Before Standarization --------------------
mean [1.         0.         0.33333333]
var  [0.66666667 0.66666667 1.55555556]
\After Standarization --------------------
mean [0. 0. 0.]
var  [1. 1. 1.]
