In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : Unit vector normalization
#

In [2]:
from sklearn import preprocessing
import numpy as np

In [4]:
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])
print(X)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [6]:
X_normalized = preprocessing.normalize(X, norm='l2')
print(X_normalized) # 행 벡터에 관해서 진행

[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [7]:
X_normalized2 = preprocessing.normalize(X, norm='l2', axis=0)
print(X_normalized2) # 열 벡터에 관해서 진행

[[ 0.4472136  -0.70710678  0.89442719]
 [ 0.89442719  0.          0.        ]
 [ 0.          0.70710678 -0.4472136 ]]
