In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : Imputation with SimpleImputer
#

In [2]:
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
X = np.array([[1, 2],
              [np.nan, 3],
              [7, 6]])
print(X)

[[ 1.  2.]
 [nan  3.]
 [ 7.  6.]]


In [4]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X_imp = imp.fit_transform(X)
print(X_imp)

[[1. 2.]
 [4. 3.]
 [7. 6.]]


In [6]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X_imp = imp.fit_transform(X)
print(X_imp)

[[1. 2.]
 [1. 3.]
 [7. 6.]]


In [7]:
imp = SimpleImputer(missing_values=np.nan, strategy='median')
X_imp = imp.fit_transform(X)
print(X_imp)

[[1. 2.]
 [4. 3.]
 [7. 6.]]
