In [1]:
#
#       2020.10.04
#       Heesung Yang
#       Pre-processing : Min-Max Normalization
#

In [2]:
from sklearn import preprocessing
import numpy as np

In [5]:
X_train = np.array([[1., -1., 4.],
                    [2., 0., 0.],
                    [0., 1., -1]])
print(X_train)

[[ 1. -1.  4.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [10]:
# Method.1
X_minmax2 = preprocessing.minmax_scale(X_train, feature_range=(-1,1), axis=0)
print(X_minmax2)

[[ 0.  -1.   1. ]
 [ 1.   0.  -0.6]
 [-1.   1.  -1. ]]


In [9]:
# Method.2
min_max_scalar = preprocessing.MinMaxScaler()
X_minmax = min_max_scalar.fit_transform(X_train)
print(X_minmax)

[[0.5 0.  1. ]
 [1.  0.5 0.2]
 [0.  1.  0. ]]
