In [22]:
# env : local 
# 2020.09.15

# importing example
import numpy as np

In [39]:
# linear structure define
vec = np.array([1, 2])
mat = np.mat([[1, 2, 3],
                [4, 5, 6]])

print(vec)
print(mat)

[1 2]
[[1 2 3]
 [4 5 6]]


In [24]:
# zero vector define
zero_vec = np.zeros(10)

print(zero_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
# diagonal matrix define
a = np.diag([1, 2, 3])

print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [49]:
# Identity matrix define
a = np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
# Triangular matrix define
A = np.mat([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

print(np.triu(A))
print(np.tril(A))

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [58]:
# Inverse matrix generating
A = np.mat([[1, 2, 4],
            [4, 5, 2],
            [7, -8, 9]])
print(A.shape)

invA = np.linalg.inv(A)
print(invA)

(3, 3)
[[-0.24302789  0.19920319  0.06374502]
 [ 0.0876494   0.07569721 -0.05577689]
 [ 0.26693227 -0.0876494   0.01195219]]


In [30]:
# random number generating
a = np.random.randn(10)
print(a)

[ 0.08764834  1.4552688   1.91635591  0.850543   -0.58289463 -0.36127435
  0.8577831   0.45427491  1.03664704  0.54601854]


In [45]:
# Summation, Subtract, Scalar multiplication and Matrix multiplication
a = np.array([1, 2])
a_mat = np.mat([[1],
                [2]])
b = np.array([3, 4])
b_mat = np.mat([[3],
                [4]])

print(a + b)
print(np.add(a, b))

print(a - b)
print(np.subtract(a, b))

print(3 * a)
print(np.multiply(3, a))


print(a_mat.T @ b_mat)
print(a_mat @ b_mat.T)

[4 6]
[4 6]
[-2 -2]
[-2 -2]
[3 6]
[3 6]
[[11]]
[[3 4]
 [6 8]]


In [9]:
# Inner product and outer product of vector
print(np.inner(a, b))
print(np.outer(a, b))

11
[[3 4]
 [6 8]]


In [10]:
# Shape of matrix
print(np.shape(vec))
print(np.shape(mat))

(2,)
(2, 3)


In [11]:
# Reshaping the matrix
dim_mat = np.shape(mat)
mat_to_vec = np.reshape(mat, dim_mat[0] * dim_mat[1])
mat_to_mat1 = np.reshape(mat, [3, 2])
mat_transpose = mat.T

print(mat)
print(mat_to_vec)
print(mat_to_mat1)
print(mat_transpose)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [31]:
# Creating matrix with vectors

# example data
x = np.array([0, 1, 2, 3])
y = np.array([0, -1, -2, -3])

# column vector oriented
xy = np.vstack([x, y])
print(xy)

# row vector oriented
xy = np.vstack([x, y]).T
print(xy)

[[ 0  1  2  3]
 [ 0 -1 -2 -3]]
[[ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]]


In [12]:
# 2-norm of vector
print(a)
print(np.linalg.norm(a))

# Frobenius norm of matrix
print(np.linalg.norm(mat))

[1 2]
2.23606797749979
9.539392014169456


In [20]:
# Correlation coefficient

# Example Data
a = np.array([1, 2, 3, 4])
b = np.array([0, 3, -1, 6])
print(np.corrcoef(a, b))

[[1.         0.57154761]
 [0.57154761 1.        ]]
[[ 1.  1. -1.  1.]
 [ 1.  1. -1.  1.]
 [-1. -1.  1. -1.]
 [ 1.  1. -1.  1.]]
